// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/krbrnrtr/krbrnrtr.proto

package krbrnrtr

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommandResponse_CommandStatus int32

const (
	CommandResponse_ACCEPTED                    CommandResponse_CommandStatus = 0
	CommandResponse_NO_HOSTS_FOUND_WITH_FILTERS CommandResponse_CommandStatus = 1
	CommandResponse_DENIED                      CommandResponse_CommandStatus = 2
	CommandResponse_INTERNAL_ERROR              CommandResponse_CommandStatus = 3
)

var CommandResponse_CommandStatus_name = map[int32]string{
	0: "ACCEPTED",
	1: "NO_HOSTS_FOUND_WITH_FILTERS",
	2: "DENIED",
	3: "INTERNAL_ERROR",
}

var CommandResponse_CommandStatus_value = map[string]int32{
	"ACCEPTED":                    0,
	"NO_HOSTS_FOUND_WITH_FILTERS": 1,
	"DENIED":                      2,
	"INTERNAL_ERROR":              3,
}

func (x CommandResponse_CommandStatus) String() string {
	return proto.EnumName(CommandResponse_CommandStatus_name, int32(x))
}

func (CommandResponse_CommandStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{5, 0}
}

type GossipMembersRequest struct {
	TagFilter            *Tags    `protobuf:"bytes,1,opt,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GossipMembersRequest) Reset()         { *m = GossipMembersRequest{} }
func (m *GossipMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GossipMembersRequest) ProtoMessage()    {}
func (*GossipMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{0}
}

func (m *GossipMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMembersRequest.Unmarshal(m, b)
}
func (m *GossipMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMembersRequest.Marshal(b, m, deterministic)
}
func (m *GossipMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMembersRequest.Merge(m, src)
}
func (m *GossipMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GossipMembersRequest.Size(m)
}
func (m *GossipMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMembersRequest proto.InternalMessageInfo

func (m *GossipMembersRequest) GetTagFilter() *Tags {
	if m != nil {
		return m.TagFilter
	}
	return nil
}

type GossipMembersResponse struct {
	Result               []*GossipMember `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GossipMembersResponse) Reset()         { *m = GossipMembersResponse{} }
func (m *GossipMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GossipMembersResponse) ProtoMessage()    {}
func (*GossipMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{1}
}

func (m *GossipMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMembersResponse.Unmarshal(m, b)
}
func (m *GossipMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMembersResponse.Marshal(b, m, deterministic)
}
func (m *GossipMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMembersResponse.Merge(m, src)
}
func (m *GossipMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GossipMembersResponse.Size(m)
}
func (m *GossipMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMembersResponse proto.InternalMessageInfo

func (m *GossipMembersResponse) GetResult() []*GossipMember {
	if m != nil {
		return m.Result
	}
	return nil
}

type GossipMember struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels               []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	IpAddress            string   `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GossipMember) Reset()         { *m = GossipMember{} }
func (m *GossipMember) String() string { return proto.CompactTextString(m) }
func (*GossipMember) ProtoMessage()    {}
func (*GossipMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{2}
}

func (m *GossipMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMember.Unmarshal(m, b)
}
func (m *GossipMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMember.Marshal(b, m, deterministic)
}
func (m *GossipMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMember.Merge(m, src)
}
func (m *GossipMember) XXX_Size() int {
	return xxx_messageInfo_GossipMember.Size(m)
}
func (m *GossipMember) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMember.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMember proto.InternalMessageInfo

func (m *GossipMember) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GossipMember) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *GossipMember) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type CommandRequest struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Arguments            []string `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	TagFilter            *Tags    `protobuf:"bytes,3,opt,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{3}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *CommandRequest) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *CommandRequest) GetTagFilter() *Tags {
	if m != nil {
		return m.TagFilter
	}
	return nil
}

type Tags struct {
	Key                  []string `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tags) Reset()         { *m = Tags{} }
func (m *Tags) String() string { return proto.CompactTextString(m) }
func (*Tags) ProtoMessage()    {}
func (*Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{4}
}

func (m *Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tags.Unmarshal(m, b)
}
func (m *Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tags.Marshal(b, m, deterministic)
}
func (m *Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tags.Merge(m, src)
}
func (m *Tags) XXX_Size() int {
	return xxx_messageInfo_Tags.Size(m)
}
func (m *Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Tags proto.InternalMessageInfo

func (m *Tags) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Tags) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type CommandResponse struct {
	CommandRequestId     string                        `protobuf:"bytes,1,opt,name=command_request_id,json=commandRequestId,proto3" json:"command_request_id,omitempty"`
	ReceiverNode         string                        `protobuf:"bytes,2,opt,name=receiver_node,json=receiverNode,proto3" json:"receiver_node,omitempty"`
	Status               CommandResponse_CommandStatus `protobuf:"varint,3,opt,name=status,proto3,enum=krbrnrtr.CommandResponse_CommandStatus" json:"status,omitempty"`
	StatusMessage        []byte                        `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	LogLocationReference string                        `protobuf:"bytes,9,opt,name=log_location_reference,json=logLocationReference,proto3" json:"log_location_reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{5}
}

func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (m *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(m, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetCommandRequestId() string {
	if m != nil {
		return m.CommandRequestId
	}
	return ""
}

func (m *CommandResponse) GetReceiverNode() string {
	if m != nil {
		return m.ReceiverNode
	}
	return ""
}

func (m *CommandResponse) GetStatus() CommandResponse_CommandStatus {
	if m != nil {
		return m.Status
	}
	return CommandResponse_ACCEPTED
}

func (m *CommandResponse) GetStatusMessage() []byte {
	if m != nil {
		return m.StatusMessage
	}
	return nil
}

func (m *CommandResponse) GetLogLocationReference() string {
	if m != nil {
		return m.LogLocationReference
	}
	return ""
}

func init() {
	proto.RegisterEnum("krbrnrtr.CommandResponse_CommandStatus", CommandResponse_CommandStatus_name, CommandResponse_CommandStatus_value)
	proto.RegisterType((*GossipMembersRequest)(nil), "krbrnrtr.GossipMembersRequest")
	proto.RegisterType((*GossipMembersResponse)(nil), "krbrnrtr.GossipMembersResponse")
	proto.RegisterType((*GossipMember)(nil), "krbrnrtr.GossipMember")
	proto.RegisterType((*CommandRequest)(nil), "krbrnrtr.CommandRequest")
	proto.RegisterType((*Tags)(nil), "krbrnrtr.Tags")
	proto.RegisterType((*CommandResponse)(nil), "krbrnrtr.CommandResponse")
}

func init() { proto.RegisterFile("protobuf/krbrnrtr/krbrnrtr.proto", fileDescriptor_d4dd7207cb026d02) }

var fileDescriptor_d4dd7207cb026d02 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0xdc, 0xf4, 0x8b, 0xe2, 0x69, 0x1a, 0xac, 0xa5, 0x44, 0xa6, 0xfc, 0x34, 0x32, 0x42,
	0xe4, 0x02, 0x02, 0x0a, 0xdc, 0x43, 0xd4, 0xb8, 0x6d, 0x44, 0xea, 0xa0, 0xb5, 0x11, 0x77, 0xac,
	0x36, 0xf6, 0xd4, 0x58, 0xb5, 0xbd, 0x61, 0x77, 0x5d, 0xa9, 0xaf, 0xcb, 0x0b, 0xf0, 0x0a, 0x28,
	0xfe, 0x49, 0x7f, 0xd4, 0x0a, 0x89, 0xbb, 0x3d, 0x67, 0x66, 0xcf, 0xcc, 0x1c, 0xcf, 0x1a, 0x06,
	0x2b, 0x29, 0xb4, 0x58, 0x16, 0x67, 0x6f, 0xcf, 0xe5, 0x52, 0xe6, 0x52, 0xcb, 0xcd, 0x61, 0x54,
	0x86, 0x48, 0xa7, 0xc1, 0x8e, 0x0b, 0x7b, 0xc7, 0x42, 0xa9, 0x64, 0x75, 0x8a, 0xd9, 0x12, 0xa5,
	0xa2, 0xf8, 0xb3, 0x40, 0xa5, 0xc9, 0x1b, 0x00, 0xcd, 0x63, 0x76, 0x96, 0xa4, 0x1a, 0xa5, 0x6d,
	0x0c, 0x8c, 0xe1, 0xce, 0xb8, 0x37, 0xda, 0xc8, 0x04, 0x3c, 0x56, 0xd4, 0xd4, 0x3c, 0x3e, 0x2a,
	0x13, 0x9c, 0x63, 0x78, 0x74, 0x4b, 0x46, 0xad, 0x44, 0xae, 0x90, 0x8c, 0xa0, 0x2d, 0x51, 0x15,
	0xa9, 0xb6, 0x8d, 0x41, 0x6b, 0xb8, 0x33, 0xee, 0x5f, 0x69, 0x5c, 0xbf, 0x40, 0xeb, 0x2c, 0x87,
	0x43, 0xf7, 0x3a, 0x4f, 0xf6, 0xa1, 0xf3, 0x43, 0x28, 0x9d, 0xf3, 0x0c, 0xcb, 0x2e, 0x4c, 0xba,
	0xc1, 0xa4, 0x0f, 0xed, 0x94, 0x2f, 0x31, 0x55, 0xf6, 0xd6, 0xa0, 0x35, 0x34, 0x69, 0x8d, 0xc8,
	0x33, 0x80, 0x64, 0xc5, 0x78, 0x14, 0x49, 0x54, 0xca, 0x6e, 0x95, 0xb7, 0xcc, 0x64, 0x35, 0xa9,
	0x08, 0xa7, 0x80, 0xde, 0xa1, 0xc8, 0x32, 0x9e, 0x47, 0xcd, 0xb0, 0x7d, 0x68, 0xf3, 0x50, 0x27,
	0x22, 0xaf, 0x4b, 0xd4, 0x88, 0x3c, 0x05, 0x93, 0xcb, 0xb8, 0xc8, 0x30, 0xd7, 0x4d, 0x8d, 0x2b,
	0xe2, 0x96, 0x45, 0xad, 0xbf, 0x59, 0x34, 0x82, 0xed, 0x35, 0x45, 0x2c, 0x68, 0x9d, 0xe3, 0x65,
	0x69, 0x87, 0x49, 0xd7, 0x47, 0xb2, 0x07, 0xff, 0x5f, 0xf0, 0xb4, 0xc0, 0xba, 0x44, 0x05, 0x9c,
	0x5f, 0x5b, 0xf0, 0x60, 0xd3, 0x67, 0xed, 0xe6, 0x6b, 0x20, 0x61, 0x45, 0x31, 0x59, 0xf5, 0xce,
	0x92, 0xa8, 0x6e, 0xda, 0x0a, 0x6f, 0x0c, 0x35, 0x8b, 0xc8, 0x0b, 0xd8, 0x95, 0x18, 0x62, 0x72,
	0x81, 0x92, 0xe5, 0x22, 0x5a, 0xeb, 0xaf, 0x13, 0xbb, 0x0d, 0xe9, 0x89, 0x08, 0xc9, 0x47, 0x68,
	0x2b, 0xcd, 0x75, 0x51, 0x19, 0xd5, 0x1b, 0xbf, 0xba, 0x9a, 0xe0, 0x56, 0xf5, 0x06, 0xfb, 0x65,
	0x3a, 0xad, 0xaf, 0x91, 0x97, 0xd0, 0xab, 0x4e, 0x2c, 0x43, 0xa5, 0x78, 0x8c, 0xf6, 0xf6, 0xc0,
	0x18, 0x76, 0xe9, 0x6e, 0xc5, 0x9e, 0x56, 0x24, 0xf9, 0x00, 0xfd, 0x54, 0xc4, 0x2c, 0x15, 0x21,
	0x5f, 0x7b, 0xcb, 0x24, 0x9e, 0xa1, 0xc4, 0x3c, 0x44, 0xdb, 0x2c, 0xbb, 0xda, 0x4b, 0x45, 0x3c,
	0xaf, 0x83, 0xb4, 0x89, 0x39, 0xdf, 0x61, 0xf7, 0x46, 0x55, 0xd2, 0x85, 0xce, 0xe4, 0xf0, 0xd0,
	0xfd, 0x12, 0xb8, 0x53, 0xeb, 0x3f, 0x72, 0x00, 0x4f, 0xbc, 0x05, 0x3b, 0x59, 0xf8, 0x81, 0xcf,
	0x8e, 0x16, 0x5f, 0xbd, 0x29, 0xfb, 0x36, 0x0b, 0x4e, 0xd8, 0xd1, 0x6c, 0x1e, 0xb8, 0xd4, 0xb7,
	0x0c, 0x02, 0xd0, 0x9e, 0xba, 0xde, 0xcc, 0x9d, 0x5a, 0x5b, 0x84, 0x40, 0x6f, 0xe6, 0x05, 0x2e,
	0xf5, 0x26, 0x73, 0xe6, 0x52, 0xba, 0xa0, 0x56, 0x6b, 0xfc, 0xdb, 0x80, 0xce, 0xe7, 0x7a, 0x5e,
	0xe2, 0x83, 0x75, 0x8c, 0xfa, 0xc6, 0x1e, 0x93, 0xe7, 0x77, 0xef, 0x6b, 0xf3, 0x4e, 0xf6, 0x0f,
	0xee, 0x8d, 0xd7, 0x9f, 0xec, 0x13, 0x98, 0xb4, 0xc8, 0x27, 0xd5, 0x42, 0xd9, 0x77, 0x98, 0x5b,
	0xe9, 0x3c, 0xbe, 0xd7, 0x76, 0x32, 0x87, 0x87, 0x1b, 0x05, 0xff, 0x32, 0x0f, 0x69, 0xf9, 0x52,
	0xfe, 0x49, 0xeb, 0x9d, 0xb1, 0x6c, 0x97, 0x7f, 0x80, 0xf7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x7e, 0xe4, 0x35, 0x5d, 0x25, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KrbrnrtrClient is the client API for Krbrnrtr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KrbrnrtrClient interface {
	GetGossipMembers(ctx context.Context, in *GossipMembersRequest, opts ...grpc.CallOption) (*GossipMembersResponse, error)
	RunAction(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	RunActionSyncResult(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (Krbrnrtr_RunActionSyncResultClient, error)
}

type krbrnrtrClient struct {
	cc *grpc.ClientConn
}

func NewKrbrnrtrClient(cc *grpc.ClientConn) KrbrnrtrClient {
	return &krbrnrtrClient{cc}
}

func (c *krbrnrtrClient) GetGossipMembers(ctx context.Context, in *GossipMembersRequest, opts ...grpc.CallOption) (*GossipMembersResponse, error) {
	out := new(GossipMembersResponse)
	err := c.cc.Invoke(ctx, "/krbrnrtr.Krbrnrtr/GetGossipMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *krbrnrtrClient) RunAction(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/krbrnrtr.Krbrnrtr/RunAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *krbrnrtrClient) RunActionSyncResult(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (Krbrnrtr_RunActionSyncResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Krbrnrtr_serviceDesc.Streams[0], "/krbrnrtr.Krbrnrtr/RunActionSyncResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &krbrnrtrRunActionSyncResultClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Krbrnrtr_RunActionSyncResultClient interface {
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type krbrnrtrRunActionSyncResultClient struct {
	grpc.ClientStream
}

func (x *krbrnrtrRunActionSyncResultClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KrbrnrtrServer is the server API for Krbrnrtr service.
type KrbrnrtrServer interface {
	GetGossipMembers(context.Context, *GossipMembersRequest) (*GossipMembersResponse, error)
	RunAction(context.Context, *CommandRequest) (*CommandResponse, error)
	RunActionSyncResult(*CommandRequest, Krbrnrtr_RunActionSyncResultServer) error
}

func RegisterKrbrnrtrServer(s *grpc.Server, srv KrbrnrtrServer) {
	s.RegisterService(&_Krbrnrtr_serviceDesc, srv)
}

func _Krbrnrtr_GetGossipMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KrbrnrtrServer).GetGossipMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/krbrnrtr.Krbrnrtr/GetGossipMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KrbrnrtrServer).GetGossipMembers(ctx, req.(*GossipMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Krbrnrtr_RunAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KrbrnrtrServer).RunAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/krbrnrtr.Krbrnrtr/RunAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KrbrnrtrServer).RunAction(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Krbrnrtr_RunActionSyncResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KrbrnrtrServer).RunActionSyncResult(m, &krbrnrtrRunActionSyncResultServer{stream})
}

type Krbrnrtr_RunActionSyncResultServer interface {
	Send(*CommandResponse) error
	grpc.ServerStream
}

type krbrnrtrRunActionSyncResultServer struct {
	grpc.ServerStream
}

func (x *krbrnrtrRunActionSyncResultServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Krbrnrtr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "krbrnrtr.Krbrnrtr",
	HandlerType: (*KrbrnrtrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGossipMembers",
			Handler:    _Krbrnrtr_GetGossipMembers_Handler,
		},
		{
			MethodName: "RunAction",
			Handler:    _Krbrnrtr_RunAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunActionSyncResult",
			Handler:       _Krbrnrtr_RunActionSyncResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/krbrnrtr/krbrnrtr.proto",
}
