// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/krbrnrtr/krbrnrtr.proto

package krbrnrtr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommandResponse_CommandStatus int32

const (
	CommandResponse_ACCEPTED                    CommandResponse_CommandStatus = 0
	CommandResponse_NO_HOSTS_FOUND_WITH_FILTERS CommandResponse_CommandStatus = 1
	CommandResponse_DENIED                      CommandResponse_CommandStatus = 2
	CommandResponse_INTERNAL_ERROR              CommandResponse_CommandStatus = 3
)

var CommandResponse_CommandStatus_name = map[int32]string{
	0: "ACCEPTED",
	1: "NO_HOSTS_FOUND_WITH_FILTERS",
	2: "DENIED",
	3: "INTERNAL_ERROR",
}

var CommandResponse_CommandStatus_value = map[string]int32{
	"ACCEPTED":                    0,
	"NO_HOSTS_FOUND_WITH_FILTERS": 1,
	"DENIED":                      2,
	"INTERNAL_ERROR":              3,
}

func (x CommandResponse_CommandStatus) String() string {
	return proto.EnumName(CommandResponse_CommandStatus_name, int32(x))
}

func (CommandResponse_CommandStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{5, 0}
}

type GossipMembersRequest struct {
	TagFilter            *Tags    `protobuf:"bytes,1,opt,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GossipMembersRequest) Reset()         { *m = GossipMembersRequest{} }
func (m *GossipMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GossipMembersRequest) ProtoMessage()    {}
func (*GossipMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{0}
}

func (m *GossipMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMembersRequest.Unmarshal(m, b)
}
func (m *GossipMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMembersRequest.Marshal(b, m, deterministic)
}
func (m *GossipMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMembersRequest.Merge(m, src)
}
func (m *GossipMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GossipMembersRequest.Size(m)
}
func (m *GossipMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMembersRequest proto.InternalMessageInfo

func (m *GossipMembersRequest) GetTagFilter() *Tags {
	if m != nil {
		return m.TagFilter
	}
	return nil
}

type GossipMembersResponse struct {
	Result               []*GossipMember `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GossipMembersResponse) Reset()         { *m = GossipMembersResponse{} }
func (m *GossipMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GossipMembersResponse) ProtoMessage()    {}
func (*GossipMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{1}
}

func (m *GossipMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMembersResponse.Unmarshal(m, b)
}
func (m *GossipMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMembersResponse.Marshal(b, m, deterministic)
}
func (m *GossipMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMembersResponse.Merge(m, src)
}
func (m *GossipMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GossipMembersResponse.Size(m)
}
func (m *GossipMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMembersResponse proto.InternalMessageInfo

func (m *GossipMembersResponse) GetResult() []*GossipMember {
	if m != nil {
		return m.Result
	}
	return nil
}

type GossipMember struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels               []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	IpAddress            string   `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GossipMember) Reset()         { *m = GossipMember{} }
func (m *GossipMember) String() string { return proto.CompactTextString(m) }
func (*GossipMember) ProtoMessage()    {}
func (*GossipMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{2}
}

func (m *GossipMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMember.Unmarshal(m, b)
}
func (m *GossipMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMember.Marshal(b, m, deterministic)
}
func (m *GossipMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMember.Merge(m, src)
}
func (m *GossipMember) XXX_Size() int {
	return xxx_messageInfo_GossipMember.Size(m)
}
func (m *GossipMember) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMember.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMember proto.InternalMessageInfo

func (m *GossipMember) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GossipMember) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *GossipMember) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type CommandRequest struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Arguments            []string `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	TagFilter            *Tags    `protobuf:"bytes,3,opt,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{3}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *CommandRequest) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *CommandRequest) GetTagFilter() *Tags {
	if m != nil {
		return m.TagFilter
	}
	return nil
}

type Tags struct {
	Key                  []string `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tags) Reset()         { *m = Tags{} }
func (m *Tags) String() string { return proto.CompactTextString(m) }
func (*Tags) ProtoMessage()    {}
func (*Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{4}
}

func (m *Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tags.Unmarshal(m, b)
}
func (m *Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tags.Marshal(b, m, deterministic)
}
func (m *Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tags.Merge(m, src)
}
func (m *Tags) XXX_Size() int {
	return xxx_messageInfo_Tags.Size(m)
}
func (m *Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Tags proto.InternalMessageInfo

func (m *Tags) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Tags) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type CommandResponse struct {
	CommandRequestId     string                        `protobuf:"bytes,1,opt,name=command_request_id,json=commandRequestId,proto3" json:"command_request_id,omitempty"`
	ReceiverNode         string                        `protobuf:"bytes,2,opt,name=receiver_node,json=receiverNode,proto3" json:"receiver_node,omitempty"`
	Status               CommandResponse_CommandStatus `protobuf:"varint,3,opt,name=status,proto3,enum=krbrnrtr.CommandResponse_CommandStatus" json:"status,omitempty"`
	StatusMessage        string                        `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	LogLocationReference string                        `protobuf:"bytes,9,opt,name=log_location_reference,json=logLocationReference,proto3" json:"log_location_reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd7207cb026d02, []int{5}
}

func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (m *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(m, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetCommandRequestId() string {
	if m != nil {
		return m.CommandRequestId
	}
	return ""
}

func (m *CommandResponse) GetReceiverNode() string {
	if m != nil {
		return m.ReceiverNode
	}
	return ""
}

func (m *CommandResponse) GetStatus() CommandResponse_CommandStatus {
	if m != nil {
		return m.Status
	}
	return CommandResponse_ACCEPTED
}

func (m *CommandResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *CommandResponse) GetLogLocationReference() string {
	if m != nil {
		return m.LogLocationReference
	}
	return ""
}

func init() {
	proto.RegisterEnum("krbrnrtr.CommandResponse_CommandStatus", CommandResponse_CommandStatus_name, CommandResponse_CommandStatus_value)
	proto.RegisterType((*GossipMembersRequest)(nil), "krbrnrtr.GossipMembersRequest")
	proto.RegisterType((*GossipMembersResponse)(nil), "krbrnrtr.GossipMembersResponse")
	proto.RegisterType((*GossipMember)(nil), "krbrnrtr.GossipMember")
	proto.RegisterType((*CommandRequest)(nil), "krbrnrtr.CommandRequest")
	proto.RegisterType((*Tags)(nil), "krbrnrtr.Tags")
	proto.RegisterType((*CommandResponse)(nil), "krbrnrtr.CommandResponse")
}

func init() { proto.RegisterFile("protobuf/krbrnrtr/krbrnrtr.proto", fileDescriptor_d4dd7207cb026d02) }

var fileDescriptor_d4dd7207cb026d02 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x52, 0xf7, 0xb3, 0xe2, 0x69, 0x1b, 0xac, 0x55, 0x89, 0x4c, 0xf9, 0x69, 0x64, 0x84,
	0xe8, 0x05, 0x04, 0x29, 0x70, 0x0f, 0x51, 0xe3, 0xb6, 0x11, 0xa9, 0x83, 0x36, 0x46, 0xdc, 0xb1,
	0xda, 0xd8, 0x13, 0x63, 0xd5, 0xf6, 0x86, 0xdd, 0x75, 0x25, 0x1e, 0x87, 0x57, 0xe3, 0x49, 0x50,
	0xfc, 0x93, 0x34, 0x51, 0x2b, 0xee, 0xf6, 0x9c, 0xf9, 0x39, 0x33, 0xc7, 0x63, 0xe8, 0x2d, 0xa5,
	0xd0, 0x62, 0x5e, 0x2c, 0xde, 0xdd, 0xc8, 0xb9, 0xcc, 0xa5, 0x96, 0xeb, 0x47, 0xbf, 0x0c, 0x91,
	0x76, 0x83, 0x5d, 0x0f, 0x8e, 0x2f, 0x85, 0x52, 0xc9, 0xf2, 0x1a, 0xb3, 0x39, 0x4a, 0x45, 0xf1,
	0x67, 0x81, 0x4a, 0x93, 0xb7, 0x00, 0x9a, 0xc7, 0x6c, 0x91, 0xa4, 0x1a, 0xa5, 0xd3, 0xea, 0xb5,
	0xce, 0x0e, 0x06, 0x9d, 0xfe, 0xba, 0x4d, 0xc0, 0x63, 0x45, 0x2d, 0xcd, 0xe3, 0x8b, 0x32, 0xc1,
	0xbd, 0x84, 0xc7, 0x3b, 0x6d, 0xd4, 0x52, 0xe4, 0x0a, 0x49, 0x1f, 0x4c, 0x89, 0xaa, 0x48, 0xb5,
	0xd3, 0xea, 0x19, 0x67, 0x07, 0x83, 0xee, 0xa6, 0xc7, 0xdd, 0x02, 0x5a, 0x67, 0xb9, 0x1c, 0x0e,
	0xef, 0xf2, 0xe4, 0x04, 0xda, 0x3f, 0x84, 0xd2, 0x39, 0xcf, 0xb0, 0x9c, 0xc2, 0xa2, 0x6b, 0x4c,
	0xba, 0x60, 0xa6, 0x7c, 0x8e, 0xa9, 0x72, 0xf6, 0x7a, 0xc6, 0x99, 0x45, 0x6b, 0x44, 0x9e, 0x03,
	0x24, 0x4b, 0xc6, 0xa3, 0x48, 0xa2, 0x52, 0x8e, 0x51, 0x56, 0x59, 0xc9, 0x72, 0x58, 0x11, 0x6e,
	0x01, 0x9d, 0x73, 0x91, 0x65, 0x3c, 0x8f, 0x9a, 0x65, 0xbb, 0x60, 0xf2, 0x50, 0x27, 0x22, 0xaf,
	0x25, 0x6a, 0x44, 0x9e, 0x81, 0xc5, 0x65, 0x5c, 0x64, 0x98, 0xeb, 0x46, 0x63, 0x43, 0xec, 0x58,
	0x64, 0xfc, 0xcb, 0xa2, 0x3e, 0xec, 0xaf, 0x28, 0x62, 0x83, 0x71, 0x83, 0xbf, 0x4a, 0x3b, 0x2c,
	0xba, 0x7a, 0x92, 0x63, 0xf8, 0xff, 0x96, 0xa7, 0x05, 0xd6, 0x12, 0x15, 0x70, 0xff, 0xec, 0xc1,
	0xa3, 0xf5, 0x9c, 0xb5, 0x9b, 0x6f, 0x80, 0x84, 0x15, 0xc5, 0x64, 0x35, 0x3b, 0x4b, 0xa2, 0x7a,
	0x68, 0x3b, 0xdc, 0x5a, 0x6a, 0x1c, 0x91, 0x97, 0x70, 0x24, 0x31, 0xc4, 0xe4, 0x16, 0x25, 0xcb,
	0x45, 0xb4, 0xea, 0xbf, 0x4a, 0x3c, 0x6c, 0x48, 0x5f, 0x44, 0x48, 0x3e, 0x82, 0xa9, 0x34, 0xd7,
	0x45, 0x65, 0x54, 0x67, 0xf0, 0x7a, 0xb3, 0xc1, 0x8e, 0x7a, 0x83, 0x67, 0x65, 0x3a, 0xad, 0xcb,
	0xc8, 0x2b, 0xe8, 0x54, 0x2f, 0x96, 0xa1, 0x52, 0x3c, 0x46, 0x67, 0xbf, 0x94, 0x39, 0xaa, 0xd8,
	0xeb, 0x8a, 0x24, 0x1f, 0xa0, 0x9b, 0x8a, 0x98, 0xa5, 0x22, 0xe4, 0x2b, 0x6f, 0x99, 0xc4, 0x05,
	0x4a, 0xcc, 0x43, 0x74, 0xac, 0x32, 0xfd, 0x38, 0x15, 0xf1, 0xa4, 0x0e, 0xd2, 0x26, 0xe6, 0x7e,
	0x87, 0xa3, 0x2d, 0x55, 0x72, 0x08, 0xed, 0xe1, 0xf9, 0xb9, 0xf7, 0x25, 0xf0, 0x46, 0xf6, 0x7f,
	0xe4, 0x14, 0x9e, 0xfa, 0x53, 0x76, 0x35, 0x9d, 0x05, 0x33, 0x76, 0x31, 0xfd, 0xea, 0x8f, 0xd8,
	0xb7, 0x71, 0x70, 0xc5, 0x2e, 0xc6, 0x93, 0xc0, 0xa3, 0x33, 0xbb, 0x45, 0x00, 0xcc, 0x91, 0xe7,
	0x8f, 0xbd, 0x91, 0xbd, 0x47, 0x08, 0x74, 0xc6, 0x7e, 0xe0, 0x51, 0x7f, 0x38, 0x61, 0x1e, 0xa5,
	0x53, 0x6a, 0x1b, 0x83, 0xdf, 0x2d, 0x68, 0x7f, 0xae, 0xf7, 0x25, 0x33, 0xb0, 0x2f, 0x51, 0x6f,
	0xdd, 0x31, 0x79, 0x71, 0xff, 0xbd, 0x36, 0xff, 0xc9, 0xc9, 0xe9, 0x83, 0xf1, 0xfa, 0x93, 0x7d,
	0x02, 0x8b, 0x16, 0xf9, 0xb0, 0x3a, 0x28, 0xe7, 0x1e, 0x73, 0xab, 0x3e, 0x4f, 0x1e, 0xb4, 0x7d,
	0x6e, 0x96, 0xff, 0xec, 0xfb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xab, 0xaa, 0x1e, 0x36, 0xd7,
	0x03, 0x00, 0x00,
}
